--------------------------------------------------------
-- Archivo creado  - lunes-mayo-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence INSTITUCION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RODRIGO"."INSTITUCION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACADEMICO
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."ACADEMICO" 
   (	"ID" NUMBER(10,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO1" VARCHAR2(100 BYTE), 
	"APELLIDO2" VARCHAR2(100 BYTE), 
	"NUMEROEMPLEADO" VARCHAR2(20 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"CORREOELECTRONICO" VARCHAR2(100 BYTE), 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE, 
	"IDREPINSTITUCION" NUMBER(10,0), 
	"IDINSTITUCION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."ADMINISTRADOR" 
   (	"ID" NUMBER(10,0), 
	"USUARIO" VARCHAR2(10 BYTE), 
	"CONTRASEÑA" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO1" VARCHAR2(50 BYTE), 
	"APELLIDO2" VARCHAR2(50 BYTE), 
	"NUMEROEMPLEADO" VARCHAR2(10 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"CORREOELECTRONICO" VARCHAR2(50 BYTE), 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ALUMNO
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."ALUMNO" 
   (	"ID" NUMBER(10,0), 
	"IDINSTITUCION" NUMBER(10,0), 
	"IDGENERO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."CATEGORIA" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"IDCUESTIONARIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUESTIONARIO
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."CUESTIONARIO" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"IDREPRESENTANTEINST" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GENERO
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."GENERO" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INSTITUCION
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."INSTITUCION" 
   (	"IMAGEN" VARCHAR2(100 BYTE), 
	"CORREOELECTRONICO" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"CALLE" VARCHAR2(100 BYTE), 
	"NUM_INT" NUMBER(9,0), 
	"NUM_EXT" NUMBER(9,0), 
	"COLONIA" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"ID" NUMBER(10,0), 
	"ACRONIMO" VARCHAR2(30 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"DIRECTOR" VARCHAR2(50 BYTE), 
	"DELEGACION" VARCHAR2(100 BYTE), 
	"IDADMINISTRADOR" NUMBER(10,0), 
	"CP" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OPCION_RESPUESTA
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."OPCION_RESPUESTA" 
   (	"ID" NUMBER(10,0), 
	"OPCION" VARCHAR2(255 BYTE), 
	"IDPREGUNTA" NUMBER(10,0), 
	"IDPUNTUACION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTA
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."PREGUNTA" 
   (	"ID" NUMBER(10,0), 
	"PREGUNTA" VARCHAR2(300 BYTE), 
	"IDSECCION" NUMBER(10,0), 
	"IDTIPO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUNTUACION
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."PUNTUACION" 
   (	"ID" NUMBER(10,0), 
	"PUNTUACION" NUMBER(10,0), 
	"IDGENERO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPRESENTANTE_INSTITUCION
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" 
   (	"ID" NUMBER(10,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO1" VARCHAR2(100 BYTE), 
	"APELLIDO2" VARCHAR2(100 BYTE), 
	"NUMEROEMPLEADO" VARCHAR2(10 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"CORREOELECTRONICO" VARCHAR2(100 BYTE), 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE, 
	"IDADMINISTRADOR" NUMBER(10,0), 
	"IDINSTITUCION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."RESPUESTA" 
   (	"ID" NUMBER(10,0), 
	"IDOPCION" NUMBER(10,0), 
	"IDALUMNO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SECCION
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."SECCION" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"IDCATEGORIA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO
--------------------------------------------------------

  CREATE TABLE "RODRIGO"."TIPO" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into RODRIGO.ACADEMICO
SET DEFINE OFF;
REM INSERTING into RODRIGO.ADMINISTRADOR
SET DEFINE OFF;
Insert into RODRIGO.ADMINISTRADOR (ID,USUARIO,"CONTRASEÑA",NOMBRE,APELLIDO1,APELLIDO2,NUMEROEMPLEADO,TELEFONO,CORREOELECTRONICO,FECHAINICIO,FECHAFIN) values (1,'admin1','admin1','admin1','admin1',null,'admin2018',1234567890,'correo@dmin1.com',to_date('04/05/18','DD/MM/RR'),null);
REM INSERTING into RODRIGO.ALUMNO
SET DEFINE OFF;
REM INSERTING into RODRIGO.CATEGORIA
SET DEFINE OFF;
REM INSERTING into RODRIGO.CUESTIONARIO
SET DEFINE OFF;
REM INSERTING into RODRIGO.GENERO
SET DEFINE OFF;
REM INSERTING into RODRIGO.INSTITUCION
SET DEFINE OFF;
Insert into RODRIGO.INSTITUCION (IMAGEN,CORREOELECTRONICO,NOMBRE,CALLE,NUM_INT,NUM_EXT,COLONIA,ESTADO,ID,ACRONIMO,TELEFONO,DIRECTOR,DELEGACION,IDADMINISTRADOR,CP) values (null,'ipn@escom.com','Escuela superior de Cómputo','av politéc',null,null,'GAM','CDMX',13,'ESCOM',123,'Quesito de Puerco','GAM',1,123);
REM INSERTING into RODRIGO.OPCION_RESPUESTA
SET DEFINE OFF;
REM INSERTING into RODRIGO.PREGUNTA
SET DEFINE OFF;
REM INSERTING into RODRIGO.PUNTUACION
SET DEFINE OFF;
REM INSERTING into RODRIGO.REPRESENTANTE_INSTITUCION
SET DEFINE OFF;
REM INSERTING into RODRIGO.RESPUESTA
SET DEFINE OFF;
REM INSERTING into RODRIGO.SECCION
SET DEFINE OFF;
REM INSERTING into RODRIGO.TIPO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007017
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007017" ON "RODRIGO"."INSTITUCION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007039
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007039" ON "RODRIGO"."ADMINISTRADOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007086
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007086" ON "RODRIGO"."REPRESENTANTE_INSTITUCION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007100
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007100" ON "RODRIGO"."ACADEMICO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007113
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007113" ON "RODRIGO"."CUESTIONARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007118
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007118" ON "RODRIGO"."CATEGORIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007123
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007123" ON "RODRIGO"."SECCION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007127
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007127" ON "RODRIGO"."TIPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007132
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007132" ON "RODRIGO"."PREGUNTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007137
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007137" ON "RODRIGO"."GENERO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007141
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007141" ON "RODRIGO"."PUNTUACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007147
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007147" ON "RODRIGO"."OPCION_RESPUESTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007158
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007158" ON "RODRIGO"."ALUMNO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007164
--------------------------------------------------------

  CREATE UNIQUE INDEX "RODRIGO"."SYS_C007164" ON "RODRIGO"."RESPUESTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger INST_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "RODRIGO"."INST_TRIG" 
before insert on institucion
for each row

begin
select INSTITUCION_SEQ.NEXTVAL
into :new.id
from dual;
end;
/
ALTER TRIGGER "RODRIGO"."INST_TRIG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACADEMICO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."ACADEMICO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("IDINSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("IDREPINSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("FECHAINICIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("CORREOELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("NUMEROEMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ACADEMICO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."ADMINISTRADOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("FECHAINICIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("CORREOELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("NUMEROEMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ADMINISTRADOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALUMNO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."ALUMNO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."ALUMNO" MODIFY ("IDGENERO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ALUMNO" MODIFY ("IDINSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."ALUMNO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."CATEGORIA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."CATEGORIA" MODIFY ("IDCUESTIONARIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."CATEGORIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."CATEGORIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUESTIONARIO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."CUESTIONARIO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."CUESTIONARIO" MODIFY ("IDREPRESENTANTEINST" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."CUESTIONARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."CUESTIONARIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GENERO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."GENERO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."GENERO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."GENERO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSTITUCION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("CP" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("DELEGACION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("COLONIA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("CALLE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("CORREOELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("ACRONIMO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."INSTITUCION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."INSTITUCION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OPCION_RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" MODIFY ("IDPUNTUACION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" MODIFY ("OPCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."PREGUNTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."PREGUNTA" MODIFY ("IDTIPO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."PREGUNTA" MODIFY ("IDSECCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."PREGUNTA" MODIFY ("PREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."PREGUNTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUNTUACION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."PUNTUACION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."PUNTUACION" MODIFY ("IDGENERO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."PUNTUACION" MODIFY ("PUNTUACION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."PUNTUACION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPRESENTANTE_INSTITUCION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("IDINSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("IDADMINISTRADOR" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("FECHAINICIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("CORREOELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("NUMEROEMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."RESPUESTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."RESPUESTA" MODIFY ("IDALUMNO" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."RESPUESTA" MODIFY ("IDOPCION" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."RESPUESTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SECCION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."SECCION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."SECCION" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."SECCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."SECCION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."TIPO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RODRIGO"."TIPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RODRIGO"."TIPO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACADEMICO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."ACADEMICO" ADD CONSTRAINT "FK_IDINSTITUCION_ACAD" FOREIGN KEY ("IDINSTITUCION")
	  REFERENCES "RODRIGO"."INSTITUCION" ("ID") ENABLE;
  ALTER TABLE "RODRIGO"."ACADEMICO" ADD CONSTRAINT "FK_IDREPINST_ACADEMICO" FOREIGN KEY ("IDREPINSTITUCION")
	  REFERENCES "RODRIGO"."REPRESENTANTE_INSTITUCION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALUMNO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."ALUMNO" ADD CONSTRAINT "FK_GENERO_ALUMNO" FOREIGN KEY ("IDGENERO")
	  REFERENCES "RODRIGO"."GENERO" ("ID") ENABLE;
  ALTER TABLE "RODRIGO"."ALUMNO" ADD CONSTRAINT "FK_INST_ALUMNO" FOREIGN KEY ("IDINSTITUCION")
	  REFERENCES "RODRIGO"."INSTITUCION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."CATEGORIA" ADD CONSTRAINT "FK_CUEST_CATEGORIA" FOREIGN KEY ("IDCUESTIONARIO")
	  REFERENCES "RODRIGO"."CUESTIONARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUESTIONARIO
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."CUESTIONARIO" ADD CONSTRAINT "FK_IDREPINST_CUEST" FOREIGN KEY ("IDREPRESENTANTEINST")
	  REFERENCES "RODRIGO"."REPRESENTANTE_INSTITUCION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSTITUCION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."INSTITUCION" ADD CONSTRAINT "FK_ADMINISTRADOR" FOREIGN KEY ("IDADMINISTRADOR")
	  REFERENCES "RODRIGO"."ADMINISTRADOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPCION_RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" ADD CONSTRAINT "FK_PREG_RESP" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "RODRIGO"."PREGUNTA" ("ID") ENABLE;
  ALTER TABLE "RODRIGO"."OPCION_RESPUESTA" ADD CONSTRAINT "FK_PUNTUA_RESP" FOREIGN KEY ("IDPUNTUACION")
	  REFERENCES "RODRIGO"."PUNTUACION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."PREGUNTA" ADD CONSTRAINT "FK_SECCION_PREG" FOREIGN KEY ("IDSECCION")
	  REFERENCES "RODRIGO"."SECCION" ("ID") ENABLE;
  ALTER TABLE "RODRIGO"."PREGUNTA" ADD CONSTRAINT "FK_TIPO_PREG" FOREIGN KEY ("IDTIPO")
	  REFERENCES "RODRIGO"."TIPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PUNTUACION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."PUNTUACION" ADD CONSTRAINT "FK_GENERO_PUNTUACION" FOREIGN KEY ("IDGENERO")
	  REFERENCES "RODRIGO"."GENERO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPRESENTANTE_INSTITUCION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" ADD CONSTRAINT "FK_ADMINISTRADOR_REPRESENTANTE" FOREIGN KEY ("IDADMINISTRADOR")
	  REFERENCES "RODRIGO"."ADMINISTRADOR" ("ID") ENABLE;
  ALTER TABLE "RODRIGO"."REPRESENTANTE_INSTITUCION" ADD CONSTRAINT "FK_INSTITUCION_RESPRESENTANTE" FOREIGN KEY ("IDINSTITUCION")
	  REFERENCES "RODRIGO"."INSTITUCION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."RESPUESTA" ADD CONSTRAINT "FK_ALUMNO_RESP" FOREIGN KEY ("IDALUMNO")
	  REFERENCES "RODRIGO"."ALUMNO" ("ID") ENABLE;
  ALTER TABLE "RODRIGO"."RESPUESTA" ADD CONSTRAINT "FK_OPCIONR_RESP" FOREIGN KEY ("IDOPCION")
	  REFERENCES "RODRIGO"."OPCION_RESPUESTA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECCION
--------------------------------------------------------

  ALTER TABLE "RODRIGO"."SECCION" ADD CONSTRAINT "FK_CATEGORIA_CUEST" FOREIGN KEY ("IDCATEGORIA")
	  REFERENCES "RODRIGO"."CATEGORIA" ("ID") ENABLE;
